### ISSUE TITLE
"detection error"

### ISSUE THREAD

**Issue by aporter3725** [umbc-research/FWHMscripts#10]
Hello Olivia this is the error I'm getting when I run the code. I can also attach the fits files I used to run it. When I ran a total of 10 fits files it stopped at 5 and gave me the error below. I can send you the fits files on discord.

``
WARNING:` NoDetectionsWarning: Sources were found, but none pass the sharpness, roundness, or peakmax criteria Iphotutils.detection.daofinder]
Traceback (most recent call last):
File "/Users/azzanporter/Downloads/obs_fits_data/FWHMscripts/main.py", line 114, in ‹module> xC, уС = sourcesListI]['xcentroid'+sfLength, sourcesList[0]['ycentroid']+sfLength
TypeError: 'NoneType' object is not
subscriptable
``

**Comment by outyprouty** [comment]
Azzan: please send the files you used and instructions for how to replicate
the error.

Roy Prouty (he/him/his)
royprouty.info
Appointment Calendar <https://calendar.app.google/d1AHDK1ihNvyLAXJ9>

The most dangerous phrase in the language is, "We've always done it this
way."

- Adm Grace Hopper

**Comment by aporter3725** [comment]
I run in the terminal, this command: `python3 main.py .` 


https://drive.google.com/drive/folders/1inI47icayk7VaTDPX7RvTX_VGBySDUNa?usp=sharing
Here is a google drive of the fits files used to run the script.

**Comment by outyprouty** [comment]
I added a try/except block to filter out files for which no appropriate fit is found. commit 29a674159e2000e5e4b7921235a97164ccb8cafd
