### ISSUE TITLE
time zones 

### ISSUE THREAD

**Issue by taraodonnell** [umbc-research/FWHMscripts#4]
The times in the log do not match the ones in the header for the same file 
example for the hd222603_seeing_ag_V_00001.fits files 
header 1/01/2023 23:23:18 
output log 2023-11-02T03:23:14.2060146
Roy says that this is probably the result of the output log being in UTC could we get the that in parentheses beside obs start time

**Comment by outyprouty** [comment]
@taraodonnell , can you confirm that the output is meeting expectations?

**Comment by taraodonnell** [comment]
time is working as expected
