### ISSUE TITLE
normalization of residuals

### ISSUE THREAD

**Issue by chiariniolivia** [umbc-research/FWHMscripts#6]
It would be easier to read the average residual data if it was normalized, i.e. between 0 and 1, this will be implemented.

**Comment by chiarini-olivia** [comment]
just implemented R^2 into code and output log, just need to see if this behaves in any unexpected ways

**Comment by outyprouty** [comment]
Any indication that this isn't working?

**Comment by chiariniolivia** [comment]
given that all the examples i have seen have this working, im gonna close this for now
